---
language: python
python:
  - "2.7"
  - "3.7"

services: docker

branches:
  only:
    - master

env:
  global:
    - ROLE_NAME=epel-repo
  matrix:
    - ANSIBLE_VERSION=">=2.7"
    - ANSIBLE_VERSION=">=2.6,<2.7"
    - ANSIBLE_VERSION=">=2.5,<2.6"

install:
  # Install Ansible and Molecule.
  - pip install ansible"${ANSIBLE_VERSION}"
  - pip install molecule
  - pip install docker

# install:
#   # Install test dependencies.
#   - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - molecule --version
  - ansible --version
  - molecule test

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
