---
- name: check if EPEL repository exist
  stat:
    path: "{{ epel_repo_file_path }}"
  register: epel_repo_file_path_result

- name: install EPEL repository
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repo_file_path_result.stat.exists

- name: import EPEL repository GPG key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repo_file_path_result.stat.exists

- name: install EPEL package
  yum:
    name: "{{ epel_package }}"
    state: present
  when: not epel_repo_file_path_result.stat.exists
