---
# ansible localhost -m setup -a 'filter=ansible_distribution'
# ansible localhost -m setup -a 'filter=ansible_os_family'
# ansible localhost -m setup -a 'filter=ansible_distribution_version'
# ansible localhost -m setup -a 'filter=ansible_distribution_major_version'

# Debug
- debug:
    msg:
      - "ansible_os_family = {{ ansible_os_family }}"
      - "ansible_distribution = {{ ansible_distribution }}"
      - "ansible_distribution_version = {{ ansible_distribution_version }}"
      - "ansible_distribution_major_version = {{ ansible_distribution_major_version }}"

# Define facts to manage amazon linux version in a easy way
- name: setting variables for amazon linux 1
  set_fact:
    amazon_linux_distribution_version: 1
  when: >
    ansible_distribution_version == '2018.03' and
    ansible_distribution_major_version == 'NA'

- name: setting variables for amazon linux 2
  set_fact:
    amazon_linux_distribution_version: 2
  when: >
    ansible_distribution_version == '(Karoo)' and
    ansible_distribution_major_version == 'NA'


# Selective include of vars
- name: include variables for CentOS/RHEL 6/7
  include_vars: "{{ item }}"
  with_first_found:
    - "redhat.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'CentOS' or
      ansible_distribution == 'RedHat'
    ) and (
      ansible_distribution_major_version == '7' or
      ansible_distribution_major_version == '6'
    )

- name: include variables for Amazon Linux 1
  include_vars: "{{ item }}"
  with_first_found:
    - "amazon-1.yml"
    - "main.yml"
  when: >
    ansible_distribution == 'Amazon' and
    amazon_linux_distribution_version == 1

- name: include variables for Amazon Linux 2
  include_vars: "{{ item }}"
  with_first_found:
    - "amazon-2.yml"
    - "main.yml"
  when: >
    ansible_distribution == 'Amazon' and
    amazon_linux_distribution_version == 2

# Debug
- debug:
    msg:
      - "epel_repo_file_path = {{ epel_repo_file_path }}"
      - "epel_repo_url = {{ epel_repo_url }}"
      - "epel_repo_gpg_key_url = {{ epel_repo_gpg_key_url }}"
      - "epel_package = {{ epel_package }}"

# Globalize vars
- name: define global vars
  set_fact:
    epel_repo_file_path: "{{ epel_repo_file_path }}"
    epel_repo_url: "{{ epel_repo_url }}"
    epel_repo_gpg_key_url: "{{ epel_repo_gpg_key_url }}"
    epel_package: "{{ epel_package }}"

# Install tasks
- name: include tasks for installation on RedHat/CentOS distribution
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'CentOS' or
      ansible_distribution == 'RedHat'
    )

- name: include tasks for installation on Amazon distribution
  include_tasks: "install-{{  ansible_distribution|lower }}.yml"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon'
